# Generated by Django 4.0.1 on 2022-01-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='nuemeroSerie',
            new_name='numeroSerie',
        ),
    ]
