# Generated by Django 4.0.1 on 2022-01-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_rename_nuemeroserie_productos_numeroserie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('autor', models.IntegerField()),
                ('genero', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='oficina',
        ),
        migrations.RemoveField(
            model_name='nosotros',
            name='cargo',
        ),
    ]
