# Generated by Django 4.0.1 on 2022-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_libros_delete_productos_delete_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='autor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='libros',
            name='genero',
            field=models.CharField(max_length=20),
        ),
    ]
