# Generated by Django 4.0.1 on 2022-01-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0004_alter_libros_autor_alter_libros_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='autor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='libros',
            name='genero',
            field=models.CharField(max_length=15),
        ),
    ]
