# Generated by Django 4.0.1 on 2022-01-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0006_rename_nosotros_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='telefono',
        ),
    ]
