# Generated by Django 4.0.1 on 2022-01-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0007_remove_contacto_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('donativo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
