# Generated by Django 4.0.1 on 2022-02-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0008_donativo_delete_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donativo',
            name='donativo',
            field=models.PositiveIntegerField(),
        ),
    ]
